apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - env:
        - name: FOO
          value: bar
        - name: BAZ
          value: bar
        - name: KUBECONEU
          value: "2024"
        image: ghcr.io/jessesuen/guestbook:v0.0.84
        name: guestbook
        ports:
        - containerPort: 3000
          name: http
